[
    {
        "key": "dbln",
        "value": "%7B%2261577578861794%22%3A%22LgM6fjAr%22%2C%2261577309504187%22%3A%22vCOgqyFA%22%2C%2261577216652947%22%3A%22WKsoLUp9%22%7D",
        "domain": "facebook.com",
        "path": "/login/device-based/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    },
    {
        "key": "datr",
        "value": "-lJyaEWcZP3lGguCsN0oS7vY",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    },
    {
        "key": "sb",
        "value": "-lJyaKhZCTjJhp_b1Iry_4lr",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    },
    {
        "key": "ps_l",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    },
    {
        "key": "ps_n",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    },
    {
        "key": "pas",
        "value": "61577578861794%3APEsGT5w8Rp%2C61577925200592%3A7zGx11ryBO%2C61577309504187%3AliHKIzqTfR%2C61577216652947%3AecxAMD1Rgl",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B680x360x2",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    },
    {
        "key": "c_user",
        "value": "61577309504187",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    },
    {
        "key": "xs",
        "value": "1%3As8qFBsDrRrcdiQ%3A2%3A1756810688%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    },
    {
        "key": "locale",
        "value": "en_US",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    },
    {
        "key": "fr",
        "value": "12XIRdTw2WwjIhznQ.AWf-gKEvKku_zDQCbcB5GUqztp719UQ8Pkmgok_Mk9s9jCpPs1g.Bor1_Q..AAA.0.0.BotzT_.AWfec-zTANvjDgdIULhjyRci13I",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    },
    {
        "key": "fbl_st",
        "value": "101731978%3BT%3A29280618",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A2911%3Btimestamp%3A1756837119",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-02T18:56:53.059Z",
        "lastAccessed": "2025-09-02T18:56:53.059Z"
    }
]
